FROM pdal/pdal:latest

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential cmake ninja-build git pkg-config \
  python3-dev python3-pip gdb \
  libgdal-dev libgeos-dev libproj-dev \
  liblzma-dev liblz4-dev libbz2-dev libzstd-dev ca-certificates \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /src
CMD ["/bin/bash"]
